"""Generate structural metrics baseline for the PatchForge codebase.

Output: docs/baseline/metrics.json
DO NOT EDIT MANUALLY — Generated by this script.
"""

import ast
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _is_public(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return not node.name.startswith("_")


def _has_docstring(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return (
        node.body
        and isinstance(node.body[0], ast.Expr)
        and isinstance(node.body[0].value, ast.Constant)
        and isinstance(node.body[0].value.value, str)
    )


def _has_return_annotation(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return node.returns is not None


def analyze_file(filepath: Path) -> dict:
    source = filepath.read_text(encoding="utf-8")

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return {"file": str(filepath), "error": "syntax_error"}

    funcs = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            end_lineno = node.end_lineno or node.lineno
            funcs.append(
                {
                    "name": node.name,
                    "line": node.lineno,
                    "end_line": end_lineno,
                    "lines": end_lineno - node.lineno + 1,
                    "is_public": _is_public(node),
                    "has_docstring": _has_docstring(node),
                    "has_return_annotation": _has_return_annotation(node),
                }
            )

    return {
        "file": str(filepath),
        "total_lines": len(source.splitlines()),
        "functions": funcs,
    }


def main():
    root = Path.cwd()
    src_dir = root / "src"
    test_dir = root / "tests"

    results = []
    for py_file in sorted(src_dir.rglob("*.py")):
        results.append(analyze_file(py_file))
    for py_file in sorted(test_dir.rglob("*.py")):
        results.append(analyze_file(py_file))

    files_over_500 = []
    files_over_1000 = []
    funcs_over_100 = 0
    funcs_over_50 = 0
    pub_no_docstring = 0
    pub_no_type_annotation = 0

    for r in results:
        if "error" in r:
            continue
        nlines = r["total_lines"]
        if nlines >= 1000:
            files_over_1000.append(f"{r['file']} ({nlines})")
        if nlines >= 500:
            files_over_500.append(f"{r['file']} ({nlines})")
        for fn in r["functions"]:
            if fn["lines"] > 100:
                funcs_over_100 += 1
            if fn["lines"] > 50:
                funcs_over_50 += 1
            if fn["is_public"] and not fn["has_docstring"]:
                pub_no_docstring += 1
            if fn["is_public"] and not fn["has_return_annotation"]:
                pub_no_type_annotation += 1

    metrics = {
        "//": "DO NOT EDIT MANUALLY — Generated by scripts/baseline_metrics.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "python_version": sys.version.split()[0],
        "total_python_files": sum(1 for r in results if "error" not in r),
        "files_over_500_lines": files_over_500,
        "files_over_1000_lines": files_over_1000,
        "functions_over_100_lines": funcs_over_100,
        "functions_over_50_lines": funcs_over_50,
        "public_funcs_no_docstring": pub_no_docstring,
        "public_funcs_no_type_annotation": pub_no_type_annotation,
    }

    out_dir = root / "docs" / "baseline"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "metrics.json"
    out_path.write_text(json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Baseline metrics written to {out_path}")
    print(json.dumps(metrics, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
